repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black .
      language: system
      types: [ python ]
    - id: pylint
      name: pylint
      entry: pylint romeways
      language: system
      types: [python]
      args:
        [
          "--disable",
          "C0114,C0115,C0116,R0903",
          "--ignore-paths",
          "tests/",
          "romeways_extras/",
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [ python ]
      pass_filenames: false
      always_run: true
      args:
        [
          "-cov=."
        ]
# mutates not use coverage to ignore dataclass slots and frozen params
#    - id: mutatest
#      name: mutatest
#      entry: mutatest
#      language: system
#      types: [ python ]
#      args:
#        [
#          "-n",
#          "100",
#          "-s",
#          ".",
#        ]
#      pass_filenames: false
#      always_run: false